#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.8.9
# In conjunction with Tcl version 8.6
#    Mar 23, 2017 08:45:54 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1 (root)
    gui_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel_1 (w)
    gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("181x188+424+117")
        top.title("PkgDecrypt-Frontend")



        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.06, rely=0.05, relheight=0.88
                , relwidth=0.88)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(text='''PkgDecrypt-Frontend''')
        self.Labelframe1.configure(width=160)

        self.Button1 = Button(self.Labelframe1)
        self.Button1.place(relx=0.06, rely=0.12, height=26, width=137)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(command=gui_support.input)
        self.Button1.configure(text='''Select PKG File''')
        self.Button1.configure(width=137)

        self.Button2 = Button(self.Labelframe1)
        self.Button2.place(relx=0.06, rely=0.3, height=26, width=137)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(command=gui_support.output)
        self.Button2.configure(text='''Select Output Folder''')
        self.Button2.configure(width=137)

        self.Button3 = Button(self.Labelframe1)
        self.Button3.place(relx=0.06, rely=0.48, height=26, width=137)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(command=gui_support.extract)
        self.Button3.configure(text='''Extract PKG''')
        self.Button3.configure(width=137)

        self.Label1 = Label(self.Labelframe1)
        self.Label1.place(relx=0.06, rely=0.67, height=48, width=136)
        self.Label1.configure(text='''CLI By: St4rk
GUI By: SilicaAndPina''')
        self.Label1.configure(width=136)






if __name__ == '__main__':
    vp_start_gui()



