#! /usr/bin/env python
#
# Support module generated by PAGE version 4.8.9
# In conjunction with Tcl version 8.6
#    Mar 23, 2017 08:45:51 PM
import os
import sys
import tkFileDialog
import tkMessageBox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

if sys.platform.__contains__('linux'):
    def openFolder(path):
        os.system('xdg-open "' + path + '"')


elif sys.platform.__contains__('win'):

    def openFolder(path):
        os.system('explorer.exe "' + path + '"')


def extract():

    try:
        print filename
    except NameError:
        tkMessageBox.showerror(title='File Selection', message='No PKG File Selected.')
    try:
        print outputFolder
    except NameError:
        global outputFolder
        outputFolder = os.path.dirname(filename)
        print outputFolder

    if sys.platform.__contains__("linux"):
        os.system("./pkg_dec '"+filename+"' '"+outputFolder+"/output'")
        os.remove("out.bin")
        tkMessageBox.showinfo(title='File Selection', message='Extraction Complete!')
    if sys.platform.__contains__("win"):
        os.system("pkg_dec.exe '"+filename+"' '"+outputFolder+"/output'")
        os.remove("out.bin")
        tkMessageBox.showinfo(title='File Selection', message='Extraction Complete!')
    sys.stdout.flush()

    openFolder(outputFolder + "/output")

def input():
    global filename
    filename = tkFileDialog.askopenfilename(title='Select file', filetypes=[('Package Files', '*.pkg')])
    sys.stdout.flush()

def output():
    global outputFolder
    outputFolder = tkFileDialog.askdirectory(title='Output Folder')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import gui
    gui.vp_start_gui()


